mklink /D entermedia ..\..\..\..\entermedia-server\webapp\WEB-INF\base\entermedia
mklink /D emfrontend ..\..\..\..\entermedia-server\webapp\WEB-INF\base\emfrontend
mklink /D system ..\..\..\..\entermedia-server\webapp\WEB-INF\base\system
mklink /D manager ..\..\..\..\entermedia-server\webapp\WEB-INF\base\manager
mklink /D emshare ..\..\..\..\app-emshare\webapp\emshare
mklink /D openedit ..\..\..\..\extension-openedit\webapp\openedit
mklink /D themes ..\..\..\..\entermedia-server\webapp\WEB-INF\base\themes
mklink /D mediadb ..\..\..\..\entermedia-server\webapp\WEB-INF\base\mediadb
mklink /D ..\bin\windows ..\..\..\..\installer_windows\webapp\WEB-INF\bin\windows
mklink /D reporting ..\..\..\..\entermedia-server\webapp\WEB-INF\base\reporting
mklink /D em-mobile ..\..\..\..\em-mobile\webapp\em-mobile